// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'l': string;
  'm': string;
  'p': string;
  's': string;
  'xl': string;
  'xs': string;
  'xxs': string;
}
export const cssExports: CssExports;
export default cssExports;
